# Site settings
title: Boyan Stoynov
description: >-
  Software Developer, Amateur Photographer
baseurl: ""
url: "https://boyan.st"

# Pagination settings
paginate: 5
paginate_path: '/blog/page:num/'

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom variables
sidebar_home_link:    true
sidebar_blog_link:    '/blog/'

personal:
  github:             https://github.com/StBoyan
  linkedin:           https://www.linkedin.com/in/boyanstoynov/
  email:              boyan.stoynov@yahoo.com
